name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Subir API
      run: |
        nohup npm start > server.log 2>&1 &
        sleep 15 # Aumentar o tempo de espera para o servidor iniciar

    - name: Verificar logs do servidor
      run: |
        echo "Logs do servidor:" && cat server.log

    - name: Wait for API to start
      run: |
        until curl -s http://localhost:3000; do
          echo "Waiting for server to start..."
          sleep 2
        done

    - name: Run tests
      run: npm test
